### ISSUE TITLE
[Feature request] option for mute/unmute current radio station 

### ISSUE THREAD

**Issue by zetok** [Pext/pext_module_radiobrowser#1]
Use case:
While listening to the radio, one might want to hear some other sound without interference. In order to do that currently stopping radio would be required, after which station would need to be painfully picked again.

Mute/unmute functionality would help with that.

**Comment by TheLastProject** [comment]
While not perfect (a bit slow in unmuting), d992d1e should cover your usecase. I left a TODO in the code to later replace it with an actual mute function.
